version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 126304775778.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t calendly-cicd-codebuild .
      - docker tag calendly-cicd-codebuild:latest 126304775778.dkr.ecr.us-east-1.amazonaws.com/calendly-cicd-codebuild:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 126304775778.dkr.ecr.us-east-1.amazonaws.com/calendly-cicd-codebuild:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files: []
